Menu page
cse110-sp23-group4/cse110-sp23-group4 pull request #100
Opened 2023-05-20 06:38 UTC by MichinoriW

Created the menu page (not completely) similar to the one on miro.

2023-05-20 19:16 UTC, Miyuki-L commented
Styled the Menu Page to fit the current Miro Board Design but kept it simple so it is easy to change once the actual design is set. 

<img width="625" alt="image" src="https://github.com/cse110-sp23-group4/cse110-sp23-group4/assets/59126064/7244ba63-32e8-43d0-949f-b7ae5b03293b">

2023-05-21 04:23 UTC, abijitj commented
The structure of the page looks good to me. Before merging, could you please write documentation for "menu-script.js" in JSDocs style? And also add some description comments to the CSS and HTML files?

2023-05-21 06:07 UTC, bimai25 requested changes

2023-05-21 06:07 UTC, bimai25 commented on source/prototyping/menu-script.js
as Abijit commented, could you add the JSDocs style documentation? thanks!

2023-05-21 23:27 UTC, bimai25 approved these changes

2023-05-21 23:27 UTC, merged